# Stage 1: Compile and Build angular codebase

# Use official node image as the base image
FROM node@sha256:a6f295c2354992f827693a2603c8b9b5b487db4da0714f5913a917ed588d6d41 as base

# Set the working directory
WORKDIR /usr/src/app

# Add the source code to app
COPY package*.json ./
RUN npm install -g npm@8.10.0
RUN npm install
COPY . .
FROM base AS build-stage-dev

RUN npm run build

# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx as dev
COPY --from=build-stage-dev /usr/src/app/dist /usr/share/nginx/html
COPY healthcheck.sh /tmp/healthcheck.sh
# Copy the default nginx.conf provided by tiangolo/node-frontend
# COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/nginx.conf